### ISSUE TITLE
Revision bump

### ISSUE THREAD

**Issue by locallycompact** [phadej/insert-ordered-containers#27]
Hi, any chance of a revision bump to http://hackage.haskell.org/package/insert-ordered-containers for the tasty bounds? This is currently failing to build downstream in nixpkgs: https://hydra.nixos.org/build/86456486

**Comment by phadej** [comment]
I'm fine if nixpkgs temporarily doesn't run tests of `insert-ordered-containers`.
- I don't want to make releases/revisions for test reasons only; they don't add much to users of the library (bounds in tests don't restrict install plans)
- I don't want to remove bounds either, because then I'll receive bug reports that tests possibly fail to compile.

I have CI. Stackage and Nixpkgs additional CI is a bonus, but I'm ok if it's not run.

I'd appreciate if nixpkgs simply omitted test bounds and tried to compile test suites, and then reported if tests fail to compile (or if new versions of test dependencies make tests fail, which is not impossible either).
