### ISSUE TITLE
Bump base, lens and possibly others for GHC 9.10.1

### ISSUE THREAD

**Issue by wolfgangwalther** [phadej/insert-ordered-containers#60]

**Comment by ysangkok** [comment]
@phadej This should now be unblocked, if it was blocked because of a missing cabal-install-3.12 release.

**Comment by phadej** [comment]
it wasn't

**Comment by ysangkok** [comment]
Just for curiosity, is there another blocker?

**Comment by phadej** [comment]
I'm not aware of any.

I do my best to update libraries I wrote & maintain. I do that in some not-very-deterministic order, but it will happen eventually. Pinging me won't make me do that faster nor change the order.

And I don't really need help in bounds bumping. I'd need to give up maintainership completely, so I don't need to worry about the library ever again. For most libraries I wouldn't, as I care about them enough. But `insert-ordered-containers` isn't a library I use anywhere myself anymore, so I'd be more than happy to transfer ownership to someone else.

**Comment by ysangkok** [comment]
Pinging @maksbotan or @swamp-agr, maybe they would be interested, since this package seems to be mostly used because it is a dependency of `swagger2` and `openapi3`.

Do you want to transfer ownership to just a single person, or wouldn't you mind to have multiple people added? If you look at e.g. Servant, it has accrued a large amount of Hackage maintainers over time. Not sure if I like that model, because it can mean that nobody feels responsible, but OTOH it doesn't seem to be abused. So you could argue that it makes it easier to avoid the package takeover process, since it is more likely that there is somebody available to hand over the maintainer bit.

**Comment by phadej** [comment]
> Do you want to transfer ownership to just a single person, or wouldn't you mind to have multiple people added? 

The keyword is **transfer**, what happens after should not be my worry.

**Comment by erikd** [comment]
@phadej I would be willing to take over maintainership of this package. Would you can transfer this repo to me? On Hackage I am ErikDeCastroLopo.

**Comment by ysangkok** [comment]
@phadej Just in case you haven't seen it, Erik has offered to take over the library. It's ok if you don't have time to transfer, we could also use the [package takeover policy](https://wiki.haskell.org/Taking_over_a_package).

**Comment by ysangkok** [comment]
@erikd Would you be willing to use the package takeover policy to get maintainer rights? Given that there is no response from phadej. I think it would be good to do since 9.10 is pretty old by now.

**Comment by erikd** [comment]
https://mail.haskell.org/pipermail/libraries/2025-April/031685.html

**Comment by hesselink** [comment]
As one of the hackage admins, I've tranferred hackage ownership to @erikd, as @phadej indicated above that he was ok tranferring ownership.
